const report = require('multiple-cucumber-html-reporter');

/**
 * Generates an HTML report from the Cucumber JSON reports.
 *
 * - jsonDir: The directory that contains the JSON report files generated by Cucumber.
 * - reportPath: The output directory where the HTML report will be saved.
 * - metadata: Provides additional information about the test environment.
 * - customData: Additional custom information to display in the report.
 */
report.generate({
  jsonDir: './reports/json', 
  reportPath: './reports/html-report/', 
  metadata: {
    browser: {
      name: 'chromium',
      version: 'Lastest' 
    },
    device: 'Local test machine',
    platform: {
      name: process.platform,
      version: process.version
    }
  },
  customData: {
    title: 'Run Info',
    data: [
      { label: 'Project', value: 'Pushing IT - Playwright' },
      { label: 'Execution Start Time', value: new Date().toLocaleString() }
    ]
  }
});
